version: '3.9'

services:
  postgres:
    image: postgres
    container_name: RizPostgres
    ports:
      - 5432:5432
    env_file:
      - ../app/.env.db
    volumes:
      - pg_db_vm:/var/lib/postgresql/data
    networks:
      - riz_network
      
  redis:
    image: redis
    container_name: RizRedis
    ports:
      - 6379:6379
    volumes:
      - redis_server_vm:/data
    networks:
      - riz_network

networks:
  riz_network:

volumes:
  pg_db_vm:
  redis_server_vm: