version: '3.9'

services:
  postgres:
    image: postgres
    container_name: RizPostgres
    ports:
      - 5432:5432
    env_file:
      - ../app/.env.db
    volumes:
      - db_volume:/var/lib/postgresql/data
      
  redis:
    image: redis
    container_name: RizRedis
    ports:
      - 6379:6379
    volumes:
      - redis_v:/data

volumes:
  db_volume:
  redis_v: