# Generated by Django 5.0.1 on 2024-06-15 05:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('verifiedEmail', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('ML', 'Male'), ('FML', 'Female'), ('None', "Don't want to identify")], default='None')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profile_picture')),
                ('idImage', models.ImageField(blank=True, null=True, upload_to='id_images')),
                ('idNumber', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('joinedOn', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=8, unique=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('validFrom', models.DateTimeField(default=django.utils.timezone.now)),
                ('validTill', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('LN', 'User Login'), ('RR', 'User Registration')], default='LN', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
