# Generated by Django 5.0.1 on 2024-01-13 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
