# Generated by Django 5.0.1 on 2024-01-13 09:52

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('BCE', 'Bicycle'), ('DB', 'Dirty Bike'), ('MC', 'Motor Cycle'), ('SC', 'Car'), ('HB', 'Hatch back'), ('CTE', 'Convertible'), ('CC', 'Coupe'), ('SSC', 'Sorts Car'), ('SUV', 'SUV'), ('PP', 'Pick up'), ('DCT', 'Double Cab Truck'), ('LY', 'Lorry'), ('TR', 'Tractor')], default='SC', max_length=3),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='role',
            field=models.CharField(choices=[('OR', 'Owner'), ('AN', 'Admin')], default='OR', max_length=5),
        ),
        migrations.AlterField(
            model_name='userauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShopMembershipToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=8, unique=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('validFrom', models.DateTimeField(default=django.utils.timezone.now)),
                ('validTill', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('OR', 'Owner'), ('AN', 'Admin')], default='AN', max_length=5)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
