# Generated by Django 5.0.1 on 2024-01-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_type_alter_shopmembership_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopmembershiptoken',
            unique_together={('token', 'shop')},
        ),
    ]
