# Generated by Django 5.0.1 on 2024-01-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shopmembershiptoken_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopmembershiptoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shopmembershiptoken',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shopmembership',
            unique_together={('user', 'shop')},
        ),
    ]
