# Generated by Django 5.0.1 on 2024-06-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_vehicleobjectid_vehicle_contentid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='brandName',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='modelName',
            new_name='model',
        ),
    ]
