# Generated by Django 5.0.1 on 2024-06-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehiclebrand_alter_vehicle_brand_vehiclemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebrand',
            name='category',
            field=models.CharField(choices=[('LND', 'Land vehicles'), ('WTR', 'Watercraft'), ('AIR', 'Aircraft')], default='LND', max_length=3),
        ),
    ]
