# Generated by Django 5.0.1 on 2024-06-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vehiclebrand_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclebrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='yom',
            field=models.DateField(null=True),
        ),
    ]
