# Generated by Django 5.0.1 on 2024-06-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vehiclebrand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='yom',
            field=models.DateTimeField(null=True),
        ),
    ]
