# Generated by Django 5.0.1 on 2024-06-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vehicle_yom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landvehicle',
            name='engineSize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
