# Generated by Django 5.0.1 on 2024-06-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_landvehicle_enginesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('HR', 'Per hour pricing rate'), ('DY', 'Per day pricing rate'), ('MH', 'Per month pricing rate')], default='DY', max_length=5)),
                ('amount', models.PositiveIntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.vehicle')),
            ],
        ),
    ]
