# Generated by Django 5.0.1 on 2024-06-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pricing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('vehicle', 'period')},
        ),
    ]
