# Generated by Django 5.0.1 on 2024-07-06 09:47

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pricing_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idImage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idNumber',
        ),
        migrations.AddField(
            model_name='landvehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=4500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlVerified', models.BooleanField(default=False)),
                ('idVerificationImage', models.ImageField(blank=True, null=True, upload_to='identificationimages')),
                ('idVerificationNumber', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('dlVerificationImage', models.ImageField(blank=True, null=True, upload_to='dlidentificationimages')),
                ('dlVerificationNumber', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.BooleanField(default=False)),
                ('latePenalty', models.BooleanField(default=False)),
                ('geographicLimit', models.BooleanField(default=False)),
                ('verifiedUser', models.BooleanField(default=True)),
                ('verifiedDl', models.BooleanField(default=False)),
                ('prohibitedUses', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.vehicle')),
            ],
        ),
    ]
