# Generated by Django 5.0.1 on 2024-07-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_idimage_remove_user_idnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proofOfOwnership', models.BooleanField(default=False)),
                ('ownershipDocuments', models.ImageField(blank=True, help_text="to prove you're the owner of th vehicle", null=True, upload_to='vehicledocuments')),
                ('roadSafe', models.BooleanField(default=False)),
                ('inspectionDocuments', models.ImageField(blank=True, null=True, upload_to='vehicledocuments')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.vehicle')),
            ],
        ),
    ]
