name: Staging Workflow

on:
    push: 
      paths-ignore:
        - 'mobile/**'
      branches: [ master ]
    workflow_dispatch:


env:
    DB_URL: postgres://postgres:postgres@localhost:5432/postgres
    DJANGO_LOG_LEVEL: WARNING
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: test@gmail.com
    EMAIL_HOST_PASSWORD: test12345678
    REDIS_URL: redis://localhost:6379

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            db:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_DB: postgres
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            
            redis:
                image: redis:7.2.3
                ports:
                  - 6379:6379
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install requirements
              working-directory: app
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Migrations and Tests
              working-directory: app
              run: |
                python manage.py migrate
                python manage.py test

            - name: Run Server and Quit
              working-directory: app
              run: python manage.py runserver &

    build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Build Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}    

        - name: Build Image and Push
          run: |
            docker build -t riz -f ./docker/Django/Dockerfile app
            docker tag riz:latest monyorojoseph/riz:v0.1.1
            docker push monyorojoseph/riz:v0.1.1